project:
  type: book
  resources: 
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"

book:
  title: "TEXTBOOK OF AGRICULTURAL STATISTICS"
  subtitle: "Very basics of statistics for students and researchers in Agriculture"
  favicon: images/papayalogo.png
  author: 
    - Dr. Pratheesh P. Gopinath
    - Dr. Manju Mary Paul
    - Dr. Adarsh V.S.
    - Mohammed Hisham
  date: "2/12/2024"
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://cleaning-data-r.ala.org.au/
  repo-url: https://github.com/AtlasOfLivingAustralia/cleaning_data
  image: images/cover.png
  image-alt: "Textbook of Agricultural Statistics"
  open-graph: 
    image: images/cover.png
    image-alt: "Textbook of Agricultural Statistics"
  chapters:
   - index.qmd
   - preface.qmd
   - intro.qmd
  twitter-card: 
    image: images/papayalogo.png
    image-alt: "Textbook of Agricultural Statistics"
    card-style: summary_large_image
  sidebar:
    logo: images/papayalogo.png
  page-footer:
    border: true
    left: |
        Published by PAPAYA publishing division of <a href="https://www.statoberry.com/papaya">![](/images/statoberry.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |
        <a href="https://www.statoberry.com/papaya">![](/images/papayalogo.png){style='width: auto; height: 90px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    right: |
        Licenced under [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/) <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">![](/images/cclogo.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
        Built with <a href="https://quarto.org/">Quarto</a>
  cover-image: images/cover.png
  
bibliography: 
  - book.bib

format:
  html:
    mainfont: Georgia
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme: 
      - theme.css
      - theme.scss
      - lumen
  pdf:
    documentclass: scrreprt

execute:
  code-annotations: hover
number-depth: 3

editor: visual

